export const CREATE_TASK = "CREATE_TASK";
export const CREATE_PROJECT = "CREATE_PROJECT";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILURE = "REGISTER_USER_FAILURE";
