export const CREATE_TASK = "CREATE_TASK";
export const CREATE_PROJECT = "CREATE_PROJECT";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILURE = "REGISTER_USER_FAILURE";

export const API_CALL_START = "API_CALL_START";
export const API_CALL_SUCCESS = "API_CALL_SUCCESS";
export const API_CALL_FAILURE = "API_CALL_FAILURE";

export const LOAD_PROJECTS = "LOAD_PROJECTS";
export const LOAD_PROJECTS_SUCCESS = "LOAD_PROJECT_SUCCESS";
export const LOAD_PROJECTS_FAILURE = "LOAD_PROJECT_FAILURE";

export const SAVE_PROJECT = "CREATE_PROJECT";
export const SAVE_PROJECT_SUCCESS = "SAVE_PROJECT_SUCCESS";
export const SAVE_PROJECT_FAILURE = "SAVE_PROJECT_FAILURE";
